[project]
name = "ebt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "einops>=0.8.1",
    "hydra-core>=1.3.2",
    "lightning>=2.6.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
